import { DatePipe, UpperCasePipe } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-movies',
  standalone: true,
  imports: [DatePipe,UpperCasePipe],
  templateUrl: './movies.component.html',
  styleUrl: './movies.component.css',
})
export class MoviesComponent {
  allMovies: any[] = [
    {
      adult: false,
      backdrop_path: '/9l1eZiJHmhr5jIlthMdJN5WYoff.jpg',
      genre_ids: [28, 35, 878],
      id: 533535,
      original_language: 'en',
      original_title: 'Deadpool & Wolverine',
      overview:
        'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
      popularity: 23022.328,
      poster_path: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
      release_date: '2024-07-24',
      title: 'Deadpool & Wolverine',
      video: false,
      vote_average: 7.913,
      vote_count: 1344,
    },
    {
      adult: false,
      backdrop_path: '/2RVcJbWFmICRDsVxRI8F5xRmRsK.jpg',
      genre_ids: [27, 878, 53],
      id: 762441,
      original_language: 'en',
      original_title: 'A Quiet Place: Day One',
      overview:
        'As New York City is invaded by alien creatures who hunt by sound, a woman named Sam fights to survive with her cat.',
      popularity: 6197.201,
      poster_path: '/yrpPYKijwdMHyTGIOd1iK1h0Xno.jpg',
      release_date: '2024-06-26',
      title: 'A Quiet Place: Day One',
      video: false,
      vote_average: 7.016,
      vote_count: 985,
    },
    {
      adult: false,
      backdrop_path: '/3q01ACG0MWm0DekhvkPFCXyPZSu.jpg',
      genre_ids: [28, 80, 53, 35],
      id: 573435,
      original_language: 'en',
      original_title: 'Bad Boys: Ride or Die',
      overview:
        'After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.',
      popularity: 5462.371,
      poster_path: '/oGythE98MYleE6mZlGs5oBGkux1.jpg',
      release_date: '2024-06-05',
      title: 'Bad Boys: Ride or Die',
      video: false,
      vote_average: 7.656,
      vote_count: 1319,
    },
    {
      adult: false,
      backdrop_path: '/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg',
      genre_ids: [16, 10751, 12, 35],
      id: 1022789,
      original_language: 'en',
      original_title: 'Inside Out 2',
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      popularity: 4449.143,
      poster_path: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
      release_date: '2024-06-11',
      title: 'Inside Out 2',
      video: false,
      vote_average: 7.629,
      vote_count: 2251,
    },
    {
      adult: false,
      backdrop_path: '/5g2n3ilC8DpYv4diJeuQ1vKG2Kb.jpg',
      genre_ids: [16, 10751, 35, 28],
      id: 519182,
      original_language: 'en',
      original_title: 'Despicable Me 4',
      overview:
        'Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.',
      popularity: 3557.455,
      poster_path: '/wWba3TaojhK7NdycRhoQpsG0FaH.jpg',
      release_date: '2024-06-20',
      title: 'Despicable Me 4',
      video: false,
      vote_average: 7.164,
      vote_count: 506,
    },
    {
      adult: false,
      backdrop_path: '/tqSg1hHiSWhHAhnjDhhevaFGsP0.jpg',
      genre_ids: [28, 18],
      id: 1066262,
      original_language: 'en',
      original_title: 'The Convert',
      overview:
        'Munro, a soldier turned lay preacher, comes to New Zealand to minister to the first British colonists, but he is converted by the powerful chief Maianui to serve a different purpose.',
      popularity: 2102.516,
      poster_path: '/e5ZqqPlhKstzB4geibpZh38w7Pq.jpg',
      release_date: '2024-03-14',
      title: 'The Convert',
      video: false,
      vote_average: 6.519,
      vote_count: 27,
    },
    {
      adult: false,
      backdrop_path: '/s5znBQmprDJJ553IMQfwEVlfroH.jpg',
      genre_ids: [28, 35, 10752],
      id: 799583,
      original_language: 'en',
      original_title: 'The Ministry of Ungentlemanly Warfare',
      overview:
        'During World War II, the British Army assigns a group of competent soldiers to carry out a mission against the Nazi forces behind enemy lines... A true story about a secret British WWII organization – the Special Operations Executive. Founded by Winston Churchill, their irregular warfare against the Germans helped to change the course of the war, and gave birth to modern black operations.',
      popularity: 2048.753,
      poster_path: '/8aF0iAKH9MJMYAZdi0Slg77RYa2.jpg',
      release_date: '2024-04-18',
      title: 'The Ministry of Ungentlemanly Warfare',
      video: false,
      vote_average: 7.165,
      vote_count: 676,
    },
    {
      adult: false,
      backdrop_path: '/Akv9GlCCMrzcDkVz4ad8MdLl9DK.jpg',
      genre_ids: [16, 35, 10751, 12],
      id: 748783,
      original_language: 'en',
      original_title: 'The Garfield Movie',
      overview:
        'Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.',
      popularity: 1773.945,
      poster_path: '/xYduFGuch9OwbCOEUiamml18ZoB.jpg',
      release_date: '2024-04-30',
      title: 'The Garfield Movie',
      video: false,
      vote_average: 7.226,
      vote_count: 669,
    },
    {
      adult: false,
      backdrop_path: '/fqv8v6AycXKsivp1T5yKtLbGXce.jpg',
      genre_ids: [878, 12, 28],
      id: 653346,
      original_language: 'en',
      original_title: 'Kingdom of the Planet of the Apes',
      overview:
        "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
      popularity: 1734.439,
      poster_path: '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
      release_date: '2024-05-08',
      title: 'Kingdom of the Planet of the Apes',
      video: false,
      vote_average: 7.175,
      vote_count: 2271,
    },
    {
      adult: false,
      backdrop_path: '/dsGwCEO8tda4FlgHKvL95f0oQbH.jpg',
      genre_ids: [16, 878, 28],
      id: 1209290,
      original_language: 'en',
      original_title: 'Justice League: Crisis on Infinite Earths Part Three',
      overview:
        'Now fully revealed as the ultimate threat to existence, the Anti-Monitor wages an unrelenting attack on the surviving Earths that struggle for survival in a pocket universe. One by one, these worlds and all their inhabitants are vaporized! On the planets that remain, even time itself is shattered, and heroes from the past join the Justice League and their rag-tag allies against the epitome of evil. But as they make their last stand, will the sacrifice of the superheroes be enough to save us all?',
      popularity: 1353.236,
      poster_path: '/a3q8NkM8uTh9E23VsbUOdDSbBeN.jpg',
      release_date: '2024-07-16',
      title: 'Justice League: Crisis on Infinite Earths Part Three',
      video: false,
      vote_average: 7.607,
      vote_count: 121,
    },
    {
      adult: false,
      backdrop_path: '/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg',
      genre_ids: [28, 12, 878],
      id: 786892,
      original_language: 'en',
      original_title: 'Furiosa: A Mad Max Saga',
      overview:
        'As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.',
      popularity: 1269.479,
      poster_path: '/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
      release_date: '2024-05-22',
      title: 'Furiosa: A Mad Max Saga',
      video: false,
      vote_average: 7.6,
      vote_count: 2452,
    },
    {
      adult: false,
      backdrop_path: '/w22yUH5pAZ3CcTjbw9GEzPd5wxs.jpg',
      genre_ids: [878, 35],
      id: 1242372,
      original_language: 'zh',
      original_title: '从21世纪安全撤离',
      overview:
        'On Planet K, unknown to anyone on Earth, three teenagers chosen by fate can travel back and forth twenty years into the future by sneezing. In the face of a shocking plot to destroy the world, they have nothing but crystal-clear stupidity and single-digit combat power, so how can they transform into heroes and fight against the super-villainous villains who are intent on destroying the world? How can they turn into heroes and fight against the super baddest villains intent on destroying the world? The "King Bomb" brothers, who look like grown-ups but have minds like no other, will save the future on behalf of the K-Star!',
      popularity: 1176.4,
      poster_path: '/nZQPbD7IEKWiUDK7s9GKHwqP88g.jpg',
      release_date: '2024-07-18',
      title: 'Escape from the 21st Century',
      video: false,
      vote_average: 8.2,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: '/tIpd7vvjoNyG6CAVqSL9gJqJSTy.jpg',
      genre_ids: [28, 53, 80],
      id: 857553,
      original_language: 'en',
      original_title: 'Johnny & Clyde',
      overview:
        "Johnny and Clyde are two serial killers who are madly in love and on an endless crime spree. Alana (Megan Fox) is the confident and cunning owner of a prosperous casino that generates tens of millions of dollars each year. Johnny and Clyde decide to assemble a ragtag group of criminals and misfits to steal from Alana's casino and pull off the heist of the century. Unfortunately for Johnny and Clyde's crew, Alana has a deadly weapon at her disposal – the monstrous slasher spirit known as Bakwas.",
      popularity: 1132.31,
      poster_path: '/cdfdR90WYCTQmYoQ0aDRZP8I2IL.jpg',
      release_date: '2023-03-23',
      title: 'Johnny & Clyde',
      video: false,
      vote_average: 4.26,
      vote_count: 25,
    },
    {
      adult: false,
      backdrop_path: '/dn3gbDpXPSwC6saMJOHkCiFA9jn.jpg',
      genre_ids: [14, 12, 10751, 35],
      id: 974262,
      original_language: 'en',
      original_title: 'Descendants: The Rise of Red',
      overview:
        "After the Queen of Hearts incites a coup on Auradon, her rebellious daughter Red and Cinderella's perfectionist daughter Chloe join forces and travel back in time to try to undo the traumatic event that set Red's mother down her villainous path.",
      popularity: 1118.774,
      poster_path: '/t9u9FWpKlZcp0Wz1qPeV5AIzDsk.jpg',
      release_date: '2024-07-11',
      title: 'Descendants: The Rise of Red',
      video: false,
      vote_average: 7,
      vote_count: 222,
    },
    {
      adult: false,
      backdrop_path: '/en971MEXui9diirXlogOrPKmsEn.jpg',
      genre_ids: [28, 12, 35],
      id: 293660,
      original_language: 'en',
      original_title: 'Deadpool',
      overview:
        'The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.',
      popularity: 1056.968,
      poster_path: '/3E53WEZJqP6aM84D8CckXx4pIHw.jpg',
      release_date: '2016-02-09',
      title: 'Deadpool',
      video: false,
      vote_average: 7.62,
      vote_count: 30394,
    },
    {
      adult: false,
      backdrop_path: '/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg',
      genre_ids: [28, 35],
      id: 1048241,
      original_language: 'en',
      original_title: 'My Spy The Eternal City',
      overview:
        'JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.',
      popularity: 1045.94,
      poster_path: '/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg',
      release_date: '2024-07-18',
      title: 'My Spy The Eternal City',
      video: false,
      vote_average: 6.7,
      vote_count: 188,
    },
    {
      adult: false,
      backdrop_path: '/9Y9wTgrMk4G1YNPDDekNk7dybwx.jpg',
      genre_ids: [28, 12, 10752],
      id: 1152624,
      original_language: 'en',
      original_title: '3 Days in Malay',
      overview:
        'Marines stationed at an airfield in Malay during WWII get wind of a coming raid by the Japanese. Unable to get reinforcements approved, they engage in a harrowing 3-day battle against enemy forces.',
      popularity: 1020.089,
      poster_path: '/hqnfqeCILvgKGWKOut5lVdxdeJh.jpg',
      release_date: '2023-08-11',
      title: '3 Days in Malay',
      video: false,
      vote_average: 5,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: '/veIyxxi5Gs8gvztLEW1Ysb8rrzs.jpg',
      genre_ids: [878, 28, 12],
      id: 823464,
      original_language: 'en',
      original_title: 'Godzilla x Kong: The New Empire',
      overview:
        'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.',
      popularity: 1002.376,
      poster_path: '/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
      release_date: '2024-03-27',
      title: 'Godzilla x Kong: The New Empire',
      video: false,
      vote_average: 7.188,
      vote_count: 3328,
    },
    {
      adult: false,
      backdrop_path: '/c3rwwFFVbkyEI6wPtpPd9lvovPW.jpg',
      genre_ids: [28, 36],
      id: 1311550,
      original_language: 'en',
      original_title: "House of Ga'a",
      overview:
        "At the height of the Oyo Empire, the ferocious Bashorun Ga'a became more powerful than the kings he enthroned, only to be undone by his own blood.",
      popularity: 986.448,
      poster_path: '/s9CBq3jjJvFtLCrvDquoj1kIz0c.jpg',
      release_date: '2024-07-26',
      title: "House of Ga'a",
      video: false,
      vote_average: 5.5,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: '/6Vbm2nHxHMlZZ199fmZtMytpFvK.jpg',
      genre_ids: [28, 53, 35],
      id: 1309923,
      original_language: 'es',
      original_title: 'No negociable',
      overview:
        'Hostage negotiator Alan Bender is called to rescue the president from a kidnapping, only to find himself also mediating to save his wife and marriage.',
      popularity: 941.472,
      poster_path: '/bHQG4UsLMFCy91gfLAFRpnCOPdP.jpg',
      release_date: '2024-07-25',
      title: 'Non Negotiable',
      video: false,
      vote_average: 6.25,
      vote_count: 41,
    },
  ];
}
